plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/mocha"
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/pa11y"
  - "@dotcom-tool-kit/lint-staged-npm"
  - "./toolkit/karma"
  - "./toolkit/demoScripts"
hooks:
  publish:tag:
    - DeployGhPages
  build:demo:
    - DemoBuilder
  test:local:
    - Eslint
    - Karma
    - Pa11y
  test:ci:
    - Eslint
    - Karma
options:
  "@dotcom-tool-kit/circleci":
    nodeVersion: "18.17-browsers"
  "@dotcom-tool-kit/eslint": {
    files: "{,!(public)/**/}*.js"
  }
  "@dotcom-tool-kit/pa11y": {
    configFile: "{,!(public)/**/}*.js"
  }
  '@dotcom-tool-kit/vault':
    team: next
    app: n-myft-ui
