version: 2.1
orbs:
  tool-kit: financial-times/dotcom-tool-kit@5
executors:
  node:
    docker:
      - image: cimg/node:18.16
  node16_20:
    docker:
      - image: cimg/node:16.20
jobs:
  deploy-gh-pages:
    docker:
      - image: cimg/base:stable
    steps:
      - tool-kit/attach-workspace
      - add_ssh_keys:
          fingerprints:
            - "83:b5:09:e4:e5:2e:74:35:c1:1b:99:73:e3:dc:b8:6f"
      - run:
          name: Publish GitHub Pages
          command: ./scripts/deploy-gh-pages.sh
  checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - tool-kit/persist-workspace:
          path: .
workflows:
  tool-kit:
    when:
      not:
        equal:
          - scheduled_pipeline
          - << pipeline.trigger_source >>
    jobs:
      - deploy-gh-pages:
          requires:
            - tool-kit/test-node
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?/
            branches:
              ignore: /.*/
      - checkout:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?/
      - waiting-for-approval:
          type: approval
          filters:
            branches:
              only: /(^renovate-.*|^nori/.*)/
      - tool-kit/setup:
          name: tool-kit/setup-<< matrix.executor >>
          requires:
            - checkout
            - waiting-for-approval
          matrix:
            parameters:
              executor:
                - node
                - node16_20
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?/
      - tool-kit/build:
          name: tool-kit/build-<< matrix.executor >>
          requires:
            - tool-kit/setup-<< matrix.executor >>
          matrix:
            parameters:
              executor:
                - node
                - node16_20
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?/
      - tool-kit/test:
          name: tool-kit/test-<< matrix.executor >>
          requires:
            - tool-kit/build-<< matrix.executor >>
          matrix:
            parameters:
              executor:
                - node
                - node16_20
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?/
      - tool-kit/publish-tag:
          requires:
            - deploy-gh-pages
            - tool-kit/test-node
          name: tool-kit/publish-tag-node
          executor: node
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?/
            branches:
              ignore: /.*/
          context: npm-publish-token
  nightly:
    when:
      and:
        - equal:
            - scheduled_pipeline
            - << pipeline.trigger_source >>
        - equal:
            - nightly
            - << pipeline.schedule.name >>
    jobs:
      - checkout
      - tool-kit/setup:
          name: tool-kit/setup-<< matrix.executor >>
          requires:
            - checkout
          matrix:
            parameters:
              executor:
                - node
                - node16_20
      - tool-kit/build:
          name: tool-kit/build-<< matrix.executor >>
          requires:
            - tool-kit/setup-<< matrix.executor >>
          matrix:
            parameters:
              executor:
                - node
                - node16_20
      - tool-kit/test:
          name: tool-kit/test-<< matrix.executor >>
          requires:
            - tool-kit/build-<< matrix.executor >>
          matrix:
            parameters:
              executor:
                - node
                - node16_20
